name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          force_orphan: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
